name: sporran
version: 8.0.0
description: A PouchDB alike for Dart. Uses lawndart for local storage and Wilt for CouchDB access.
repository: https://github.com/shamblett/sporran
homepage: https://github.com/shamblett/sporran

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  wilt: '^7.1.0'
  json_object_lite: '^4.0.1'
  web: '>=0.5.0 <2.0.0'
  indexed_db: '^1.0.0'

dev_dependencies:
  test: '^1.25.12'
  build_runner: '^2.4.13'
  build_test: '^2.2.2'
  build_web_compilers: '^4.0.11'
  lints: '^5.1.0'
  dart_code_metrics_presets: '^2.22.0'


