name: sporran
version: 3.0.0
author: S. Hamblett <steve.hamblett@linux.com>
description: A PouchDB alike for Dart
homepage: https://github.com/shamblett/sporran

environment:
  sdk: ">=1.8.0  <2.0.0-dev.infinity"

dependencies:
  browser: any
  lawndart: '>=0.6.4'
  wilt: '>=3.0.0'

dev_dependencies:
  test: '^0.12.0'
  coverage: '^0.7.3'
  dart_dev: '^1.0.0'
  dart_style: '>=0.2.0 <0.3.0'
  dartdoc: '>=0.8.0 <=0.10.0'
