name: sporran
version: 6.2.0
description: A PouchDB alike for Dart. Uses lawndart for local storage and Wilt for CouchDB access.
homepage: https://github.com/shamblett/sporran

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  wilt: '^6.0.1'
  json_object_lite: '^3.0.2'

dev_dependencies:
  test: '^1.21.5'
  build_runner: '^2.2.0'
  build_test: '^2.1.5'
  build_web_compilers: '^3.2.5'
  lints: '^2.0.0'


