name: sporran
version: 6.0.0
description: A PouchDB alike for Dart. Uses lawndart for local storage and Wilt for CouchDB access.
homepage: https://github.com/shamblett/sporran

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  wilt: '^6.0.0'
  json_object_lite: '^3.0.0'

dev_dependencies:
  test: '^1.16.8'
  pedantic: '^1.11.0'
  build_runner: '^1.12.1'
  build_test: '^2.0.0'
  build_web_compilers: '^2.16.0'

