name: sporran
version: 7.0.1
description: A PouchDB alike for Dart. Uses lawndart for local storage and Wilt for CouchDB access.
repository: https://github.com/shamblett/sporran
homepage: https://github.com/shamblett/sporran

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  wilt: '^7.1.0'
  json_object_lite: '^4.0.1'
  web: '>=0.5.0 <2.0.0'

dev_dependencies:
  test: '^1.25.8'
  build_runner: '^2.4.13'
  build_test: '^2.2.2'
  build_web_compilers: '^4.0.11'
  lints: '^5.0.0'


